version: 0.2
phases:
    pre_build:
        commands:
         - echo Restore started on `date`
         - dotnet restore src/JsPlayground2021/JsPlayground2021.Web/JsPlayground2021.Web.csproj
    build:
        commands:
        - echo Build started on `date`
        - dotnet publish -c release -o ./build_output src/JsPlayground2021/JsPlayground2021.Web/JsPlayground2021.Web.csproj
artifacts:
    files:
        #  * is a simple, non-recursive wildcard representing zero or more characters which you can use for paths and file names.
        # ** is a recursive wildcard which can only be used with paths, not file names.
        - '**/*'                                                    # what does the slash do?
        # - '**'                                                      # will match all files in root and all files in all child directories, recursively
        # - '/wwwroot/**'
        - '/assets/css/bootstrap5.1.3/bootswatch/simplex/**/*.min.css'        # will match all files in simplex folder and all files in all child directories, recursively
    base-directory: './build_output'
