version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore src/JsPlayground2021/JsPlayground2021.Web/JsPlayground2021.Web.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output src/JsPlayground2021/JsPlayground2021.Web/JsPlayground2021.Web.csproj
artifacts:
  files:
    - ./**/*
  base-directory: './build_output'